const messages={
 en:{saved:'Saved.',saving:'Saving…',failed:'Unable to save. Please try again.',locked:'This match is closed for predictions.',invalid:'Enter two non-negative whole-number scores.',loading:'Loading…',you:'You',notSynced:'Not synced yet',noMatches:'No synced matches yet.',choose:'Select an active tournament.',create:'Creating…',join:'Joining…',emptyPools:'Create your first private pool and share the invitation code.',noActive:'No active tournaments are available yet.',syncDone:'Synced matches: ',partial:'Some tournaments could not be synced: ',created:'Tournament saved.',name:'Name',edition:'Edition',category:'Category',source:'Source',title:'Title',summary:'Summary',sourceUrl:'Source URL',imageUrl:'Image URL',featured:'Featured story',publish:'Publish news',published:'Published.',archived:'Archived.',archive:'Archive news',copy:'Invitation code copied.',noUpcoming:'No upcoming matches are available.',connection:'Unable to connect to the database. Please check your connection and try again.',back:'Return home',unverified:'Not verified',dataLoaded:'Database data loaded',sportsLimited:'Coverage depends on the sports-data provider. Sync status is shown above.'},
 es:{saved:'Guardado.',saving:'Guardando…',failed:'No se pudo guardar. Inténtalo de nuevo.',locked:'Este partido está cerrado para pronósticos.',invalid:'Ingresa dos marcadores enteros y no negativos.',loading:'Cargando…',you:'Tú',notSynced:'Sin sincronizar',noMatches:'Aún no hay partidos sincronizados.',choose:'Selecciona un torneo activo.',create:'Creando…',join:'Uniéndose…',emptyPools:'Crea tu primera quiniela privada y comparte el código de invitación.',noActive:'Aún no hay torneos activos disponibles.',syncDone:'Partidos sincronizados: ',partial:'No se pudieron sincronizar algunos torneos: ',created:'Torneo guardado.',name:'Nombre',edition:'Edición',category:'Categoría',source:'Fuente',title:'Título',summary:'Resumen',sourceUrl:'URL de la fuente',imageUrl:'URL de la imagen',featured:'Noticia destacada',publish:'Publicar noticia',published:'Publicado.',archived:'Archivado.',archive:'Archivar noticia',copy:'Código de invitación copiado.',noUpcoming:'No hay próximos partidos disponibles.',connection:'No se pudo conectar con la base de datos. Revisa tu conexión e inténtalo de nuevo.',back:'Volver al inicio',unverified:'Sin verificar',dataLoaded:'Datos cargados de la base de datos',sportsLimited:'La cobertura depende del proveedor de datos deportivos. El estado de sincronización aparece arriba.'},
 fr:{saved:'Enregistré.',saving:'Enregistrement…',failed:'Impossible d’enregistrer. Réessayez.',locked:'Les pronostics sont fermés pour ce match.',invalid:'Saisissez deux scores entiers positifs ou nuls.',loading:'Chargement…',you:'Vous',notSynced:'Non synchronisé',noMatches:'Aucun match synchronisé pour le moment.',choose:'Sélectionnez un tournoi actif.',create:'Création…',join:'Inscription…',emptyPools:'Créez votre premier pool privé et partagez le code d’invitation.',noActive:'Aucun tournoi actif disponible pour le moment.',syncDone:'Matchs synchronisés : ',partial:'Certains tournois n’ont pas été synchronisés : ',created:'Tournoi enregistré.',name:'Nom',edition:'Édition',category:'Catégorie',source:'Source',title:'Titre',summary:'Résumé',sourceUrl:'URL de la source',imageUrl:'URL de l’image',featured:'Article à la une',publish:'Publier l’article',published:'Publié.',archived:'Archivé.',archive:'Archiver l’article',copy:'Code d’invitation copié.',noUpcoming:'Aucun match à venir disponible.',connection:'Impossible de se connecter à la base de données. Vérifiez votre connexion et réessayez.',back:'Retour à l’accueil',unverified:'Non vérifié',dataLoaded:'Données chargées de la base de données',sportsLimited:'La couverture dépend du fournisseur de données sportives. Le statut de synchronisation est affiché ci-dessus.'}
}
export const qaCopy=locale=>messages[locale]||messages.en
export function validScores(home,away){return [home,away].every(v=>v!==''&&v!=null&&Number.isSafeInteger(Number(v))&&Number(v)>=0&&Number(v)<=2147483647)}
export function predictionOpen(match,now=Date.now()){return Boolean(match&&match.status==='scheduled'&&new Date(match.kickoff).valueOf()>now)}
export function syncSummary(data,locale){
 const c=qaCopy(locale),results=data?.results||[data?.result].filter(Boolean)
 const failures=results.filter(r=>r.error||r.skipped)
 if(failures.length)throw new Error(c.partial+failures.map(r=>`${r.name||r.id}: ${r.error||r.reason}`).join('; '))
 return c.syncDone+results.reduce((n,r)=>n+(r.matches||0),0)
}
