-- PoolKick production schema for Supabase
-- Run this entire file in Supabase SQL Editor on a new project.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Player',
  avatar text not null default '⚽',
  country text default '',
  country_flag text default '🌎',
  favorite_team text default '',
  role text not null default 'player' check (role in ('player','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.tournaments (
  id text primary key,
  slug text unique not null,
  name text not null,
  short_name text not null,
  edition text not null,
  icon text not null default '⚽',
  accent text not null default '#0f8069',
  status text not null default 'coming' check (status in ('active','coming','archived')),
  format text default '',
  description text default ''
);

create table if not exists public.teams (
  id text primary key,
  tournament_id text not null references public.tournaments(id) on delete cascade,
  name text not null,
  code text not null,
  flag text default '⚽',
  badge text default '',
  logo_url text
);

create table if not exists public.matches (
  id text primary key,
  tournament_id text not null references public.tournaments(id) on delete cascade,
  stage text not null,
  round text not null,
  home_team_id text references public.teams(id),
  away_team_id text references public.teams(id),
  kickoff timestamptz not null,
  status text not null default 'scheduled' check (status in ('scheduled','live','finished','postponed','cancelled')),
  home_score int,
  away_score int,
  external_id text unique,
  updated_at timestamptz not null default now()
);

create table if not exists public.pools (
  id text primary key,
  tournament_id text not null references public.tournaments(id),
  name text not null,
  code text unique not null,
  commissioner_id uuid not null references public.profiles(id) on delete cascade,
  visibility text not null default 'private' check (visibility in ('private','public')),
  scoring text not null default 'classic' check (scoring in ('classic','simple')),
  created_at timestamptz not null default now()
);

create table if not exists public.pool_members (
  pool_id text not null references public.pools(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key(pool_id,user_id)
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  pool_id text not null references public.pools(id) on delete cascade,
  match_id text not null references public.matches(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  home_score int not null check (home_score >= 0),
  away_score int not null check (away_score >= 0),
  points int,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(pool_id,match_id,user_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  pool_id text not null references public.pools(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  text text not null check (char_length(text) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  text text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

-- New auth users automatically receive a profile.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,display_name)
  values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1)));
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Scoring function used by the database and safe to call after a final result.
create or replace function public.recalculate_match_points(target_match_id text)
returns void language plpgsql security definer set search_path=public as $$
declare r record; p record; exact_pts int; diff_pts int; outcome_pts int; actual_outcome text; pred_outcome text;
begin
  select * into r from matches where id=target_match_id and status='finished';
  if not found then return; end if;
  actual_outcome := case when r.home_score=r.away_score then 'D' when r.home_score>r.away_score then 'H' else 'A' end;
  for p in select pr.*, po.scoring from predictions pr join pools po on po.id=pr.pool_id where pr.match_id=target_match_id loop
    if p.scoring='simple' then exact_pts:=3; diff_pts:=1; outcome_pts:=1; else exact_pts:=5; diff_pts:=3; outcome_pts:=2; end if;
    pred_outcome := case when p.home_score=p.away_score then 'D' when p.home_score>p.away_score then 'H' else 'A' end;
    update predictions set points = case
      when p.home_score=r.home_score and p.away_score=r.away_score then exact_pts
      when p.scoring='classic' and (p.home_score-p.away_score)=(r.home_score-r.away_score) and pred_outcome=actual_outcome then diff_pts
      when pred_outcome=actual_outcome then outcome_pts else 0 end,
      updated_at=now()
    where id=p.id;
  end loop;
end; $$;

-- Prevent prediction inserts/updates after kickoff at database level.
create or replace function public.guard_prediction_deadline()
returns trigger language plpgsql as $$
declare ko timestamptz;
begin
  select kickoff into ko from matches where id=new.match_id;
  if ko <= now() then raise exception 'Prediction deadline has passed'; end if;
  return new;
end; $$;

drop trigger if exists prediction_deadline_guard on public.predictions;
create trigger prediction_deadline_guard before insert or update on public.predictions
for each row execute procedure public.guard_prediction_deadline();

-- RLS
alter table public.profiles enable row level security;
alter table public.tournaments enable row level security;
alter table public.teams enable row level security;
alter table public.matches enable row level security;
alter table public.pools enable row level security;
alter table public.pool_members enable row level security;
alter table public.predictions enable row level security;
alter table public.comments enable row level security;
alter table public.notifications enable row level security;

create or replace function public.is_admin(uid uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from profiles where id=uid and role='admin');
$$;

create or replace function public.is_pool_member(pid text, uid uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from pool_members where pool_id=pid and user_id=uid);
$$;

-- Join private pools without exposing the full private-pool catalogue.
create or replace function public.join_pool_by_code(join_code text)
returns text language plpgsql security definer set search_path=public as $$
declare pid text;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select id into pid from pools where upper(code)=upper(trim(join_code)) limit 1;
  if pid is null then return null; end if;
  insert into pool_members(pool_id,user_id) values(pid,auth.uid()) on conflict do nothing;
  return pid;
end; $$;

-- Automatic scoring persistence whenever an administrator finalizes a match.
create or replace function public.on_match_finished()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.status='finished' and (old.status is distinct from new.status or old.home_score is distinct from new.home_score or old.away_score is distinct from new.away_score) then
    perform public.recalculate_match_points(new.id);
  end if;
  return new;
end; $$;

drop trigger if exists score_finished_match on public.matches;
create trigger score_finished_match after update on public.matches
for each row execute procedure public.on_match_finished();

-- Read policies
create policy "profiles authenticated read" on public.profiles for select to authenticated using (true);
create policy "catalogue public read" on public.tournaments for select using (true);
create policy "teams public read" on public.teams for select using (true);
create policy "matches public read" on public.matches for select using (true);
create policy "pools member read" on public.pools for select to authenticated using (commissioner_id=auth.uid() or public.is_pool_member(id,auth.uid()) or public.is_admin(auth.uid()));
create policy "members pool read" on public.pool_members for select to authenticated using (user_id=auth.uid() or public.is_pool_member(pool_id,auth.uid()) or public.is_admin(auth.uid()));
create policy "predictions fair read" on public.predictions for select to authenticated using (
  public.is_admin(auth.uid()) or
  (public.is_pool_member(pool_id,auth.uid()) and (
    user_id=auth.uid() or exists(select 1 from matches m where m.id=match_id and m.kickoff<=now())
  ))
);
create policy "comments member read" on public.comments for select to authenticated using (public.is_pool_member(pool_id,auth.uid()) or public.is_admin(auth.uid()));
create policy "own notifications read" on public.notifications for select to authenticated using (auth.uid()=user_id or public.is_admin(auth.uid()));

-- User write policies
create policy "profile owner update" on public.profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id);
create policy "create pool" on public.pools for insert to authenticated with check (auth.uid()=commissioner_id);
create policy "commissioner update pool" on public.pools for update to authenticated using (auth.uid()=commissioner_id) with check (auth.uid()=commissioner_id);
create policy "creator membership insert" on public.pool_members for insert to authenticated with check (auth.uid()=user_id and exists(select 1 from pools p where p.id=pool_id and p.commissioner_id=auth.uid()));
create policy "leave own pool" on public.pool_members for delete to authenticated using (auth.uid()=user_id);
create policy "own prediction insert" on public.predictions for insert to authenticated with check (auth.uid()=user_id and public.is_pool_member(pool_id,auth.uid()));
create policy "own prediction update" on public.predictions for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id and public.is_pool_member(pool_id,auth.uid()));
create policy "member comment insert" on public.comments for insert to authenticated with check (auth.uid()=user_id and public.is_pool_member(pool_id,auth.uid()));
create policy "own notification update" on public.notifications for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);

-- Admin write policies
create policy "admin tournament write" on public.tournaments for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admin team write" on public.teams for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "admin match write" on public.matches for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

-- Prevent a normal authenticated user from promoting their own role via the API.
revoke update on public.profiles from authenticated;
grant update(display_name,avatar,country,country_flag,favorite_team) on public.profiles to authenticated;
grant select on public.profiles to authenticated;

grant execute on function public.join_pool_by_code(text) to authenticated;
revoke all on function public.recalculate_match_points(text) from public, anon;
grant execute on function public.recalculate_match_points(text) to authenticated;

-- Seed the initial tournament catalogue.
insert into public.tournaments(id,slug,name,short_name,edition,icon,accent,status,format,description) values
('t1','world-cup-2026','World Cup','WC 2026','2026','🌎','#ff4d4f','active','48 teams · group stage + knockout','The biggest national-team tournament in football.'),
('t2','champions-league-2026','Champions League','UCL','2026/27','🏆','#6f7cff','active','League phase + knockout','Europe’s premier club competition.'),
('t3','euro-2028','EURO','EURO','2028','🇪🇺','#00a8ff','coming','Group stage + knockout','Europe’s national-team championship.'),
('t4','copa-america-2028','Copa América','COPA','2028','🌎','#20c997','coming','Group stage + knockout','South America’s flagship national-team tournament.')
on conflict(id) do update set name=excluded.name,edition=excluded.edition,status=excluded.status;

insert into public.teams(id,tournament_id,name,code,flag,badge) values
('tm1','t1','Canada','CAN','🇨🇦','CAN'),('tm2','t1','Mexico','MEX','🇲🇽','MEX'),('tm3','t1','Colombia','COL','🇨🇴','COL'),('tm4','t1','Argentina','ARG','🇦🇷','ARG'),
('tm5','t1','Brazil','BRA','🇧🇷','BRA'),('tm6','t1','Spain','ESP','🇪🇸','ESP'),('tm7','t1','France','FRA','🇫🇷','FRA'),('tm8','t1','USA','USA','🇺🇸','USA'),
('tm9','t2','Real Madrid','RMA','⚪','RMA'),('tm10','t2','Manchester City','MCI','🔵','MCI'),('tm11','t2','Bayern Munich','FCB','🔴','FCB'),('tm12','t2','Paris SG','PSG','🔷','PSG')
on conflict(id) do nothing;

-- Use future demo dates so these fixtures are immediately usable after setup.
insert into public.matches(id,tournament_id,stage,round,home_team_id,away_team_id,kickoff,status) values
('m1','t1','Group Stage','Matchday 1','tm1','tm2',now()+interval '2 days','scheduled'),
('m2','t1','Group Stage','Matchday 1','tm3','tm4',now()+interval '2 days 2 hours','scheduled'),
('m3','t1','Group Stage','Matchday 1','tm5','tm6',now()+interval '3 days','scheduled'),
('m4','t1','Group Stage','Matchday 1','tm7','tm8',now()+interval '3 days 3 hours','scheduled'),
('m9','t2','League Phase','Matchday 1','tm9','tm10',now()+interval '4 days','scheduled'),
('m10','t2','League Phase','Matchday 1','tm11','tm12',now()+interval '4 days 2 hours','scheduled')
on conflict(id) do nothing;

-- After creating Marlon's production user, promote it once with:
-- Find Marlon's auth UUID in Authentication > Users, then run:
-- update public.profiles set role='admin' where id='MARLON_AUTH_UUID_HERE';


-- PoolKick V2: multilingual newsfeed + realtime updates
-- Safe incremental migration for an existing V1 Supabase project.

create table if not exists public.news_articles (
  id text primary key,
  category text not null default 'platform' check (category in ('world-cup','champions','copa','euro','platform')),
  title_en text not null,
  title_es text not null default '',
  title_fr text not null default '',
  summary_en text not null default '',
  summary_es text not null default '',
  summary_fr text not null default '',
  source_name text not null default 'PoolKick',
  source_url text,
  image_url text,
  featured boolean not null default false,
  status text not null default 'published' check (status in ('draft','published','archived')),
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.news_articles enable row level security;

drop policy if exists "news public read" on public.news_articles;
create policy "news public read" on public.news_articles
for select using (status='published' or public.is_admin(auth.uid()));

drop policy if exists "admin news write" on public.news_articles;
create policy "admin news write" on public.news_articles
for all to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

grant select on public.news_articles to anon, authenticated;
grant insert, update, delete on public.news_articles to authenticated;

insert into public.news_articles
(id,category,title_en,title_es,title_fr,summary_en,summary_es,summary_fr,source_name,featured,status,published_at)
values
('news1','world-cup','World Cup prediction hub is ready','El centro de pronósticos del Mundial está listo','Le centre de pronostics de la Coupe du monde est prêt','Create a private World Cup pool, invite friends and lock every score prediction at kickoff.','Crea una quiniela privada del Mundial, invita amigos y bloquea cada pronóstico al inicio del partido.','Créez un pool privé pour la Coupe du monde, invitez vos amis et verrouillez chaque pronostic au coup d’envoi.','PoolKick',true,'published',now()-interval '1 day'),
('news2','champions','Champions League pools are open','Ya puedes crear quinielas de Champions League','Les pools de Ligue des champions sont ouverts','The tournament catalogue already supports a separate Champions League competition and leaderboard.','El catálogo ya permite una competencia y ranking independiente para la Champions League.','Le catalogue prend déjà en charge une compétition et un classement distincts pour la Ligue des champions.','PoolKick',false,'published',now()-interval '2 days'),
('news3','platform','PoolKick launches ad-free','PoolKick inicia sin publicidad','PoolKick démarre sans publicité','The first release is designed without ads. Voluntary donations can support hosting and future improvements.','La primera versión está diseñada sin anuncios. Las donaciones voluntarias pueden apoyar el hosting y futuras mejoras.','La première version est conçue sans publicité. Les dons volontaires peuvent soutenir l’hébergement et les futures améliorations.','PoolKick',false,'published',now()-interval '3 days')
on conflict(id) do update set
category=excluded.category,title_en=excluded.title_en,title_es=excluded.title_es,title_fr=excluded.title_fr,
summary_en=excluded.summary_en,summary_es=excluded.summary_es,summary_fr=excluded.summary_fr,
source_name=excluded.source_name,featured=excluded.featured,status=excluded.status;

-- Postgres Changes powers live pool chat, score updates and news refreshes.
do $$
declare t text;
begin
  foreach t in array array['comments','predictions','matches','news_articles']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname='supabase_realtime' and schemaname='public' and tablename=t
    ) then
      execute format('alter publication supabase_realtime add table public.%I',t);
    end if;
  end loop;
end $$;


-- PoolKick V2 security and performance hardening

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated;

create or replace function private.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1 from public.profiles
    where id = uid and role = 'admin'
  );
$$;

create or replace function private.is_pool_member(pid text, uid uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1 from public.pool_members
    where pool_id = pid and user_id = uid
  );
$$;

revoke all on function private.is_admin(uuid) from public;
revoke all on function private.is_pool_member(text,uuid) from public;
grant execute on function private.is_admin(uuid) to anon, authenticated;
grant execute on function private.is_pool_member(text,uuid) to authenticated;

create or replace function private.join_pool_by_code_impl(join_code text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  pid text;
  uid uuid;
begin
  uid := auth.uid();
  if uid is null then
    raise exception 'Authentication required';
  end if;

  select id into pid
  from public.pools
  where code = upper(trim(join_code))
  limit 1;

  if pid is null then return null; end if;

  insert into public.pool_members(pool_id,user_id)
  values(pid,uid)
  on conflict do nothing;

  return pid;
end;
$$;

revoke all on function private.join_pool_by_code_impl(text) from public;
grant execute on function private.join_pool_by_code_impl(text) to authenticated;

create or replace function public.join_pool_by_code(join_code text)
returns text
language sql
security invoker
set search_path = ''
as $$
  select private.join_pool_by_code_impl(join_code);
$$;

revoke all on function public.join_pool_by_code(text) from public, anon;
grant execute on function public.join_pool_by_code(text) to authenticated;

create or replace function public.guard_prediction_deadline()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  ko timestamptz;
begin
  select kickoff into ko
  from public.matches
  where id = new.match_id;

  if ko <= now() then
    raise exception 'Prediction deadline has passed';
  end if;

  return new;
end;
$$;

revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.on_match_finished() from public, anon, authenticated;
revoke all on function public.recalculate_match_points(text) from public, anon, authenticated;
revoke all on function public.rls_auto_enable() from public, anon, authenticated;

drop policy if exists "pools member read" on public.pools;
create policy "pools member read" on public.pools
for select to authenticated
using (
  commissioner_id = (select auth.uid())
  or private.is_pool_member(id,(select auth.uid()))
  or private.is_admin((select auth.uid()))
);

drop policy if exists "members pool read" on public.pool_members;
create policy "members pool read" on public.pool_members
for select to authenticated
using (
  user_id = (select auth.uid())
  or private.is_pool_member(pool_id,(select auth.uid()))
  or private.is_admin((select auth.uid()))
);

drop policy if exists "predictions fair read" on public.predictions;
create policy "predictions fair read" on public.predictions
for select to authenticated
using (
  private.is_admin((select auth.uid()))
  or (
    private.is_pool_member(pool_id,(select auth.uid()))
    and (
      user_id = (select auth.uid())
      or exists(
        select 1 from public.matches m
        where m.id = match_id and m.kickoff <= now()
      )
    )
  )
);

drop policy if exists "comments member read" on public.comments;
create policy "comments member read" on public.comments
for select to authenticated
using (
  private.is_pool_member(pool_id,(select auth.uid()))
  or private.is_admin((select auth.uid()))
);

drop policy if exists "own notifications read" on public.notifications;
create policy "own notifications read" on public.notifications
for select to authenticated
using (
  (select auth.uid()) = user_id
  or private.is_admin((select auth.uid()))
);

drop policy if exists "profile owner update" on public.profiles;
create policy "profile owner update" on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "create pool" on public.pools;
create policy "create pool" on public.pools
for insert to authenticated
with check ((select auth.uid()) = commissioner_id);

drop policy if exists "commissioner update pool" on public.pools;
create policy "commissioner update pool" on public.pools
for update to authenticated
using ((select auth.uid()) = commissioner_id)
with check ((select auth.uid()) = commissioner_id);

drop policy if exists "creator membership insert" on public.pool_members;
create policy "creator membership insert" on public.pool_members
for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and exists(
    select 1 from public.pools p
    where p.id = pool_id
      and p.commissioner_id = (select auth.uid())
  )
);

drop policy if exists "leave own pool" on public.pool_members;
create policy "leave own pool" on public.pool_members
for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "own prediction insert" on public.predictions;
create policy "own prediction insert" on public.predictions
for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and private.is_pool_member(pool_id,(select auth.uid()))
);

drop policy if exists "own prediction update" on public.predictions;
create policy "own prediction update" on public.predictions
for update to authenticated
using ((select auth.uid()) = user_id)
with check (
  (select auth.uid()) = user_id
  and private.is_pool_member(pool_id,(select auth.uid()))
);

drop policy if exists "member comment insert" on public.comments;
create policy "member comment insert" on public.comments
for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and private.is_pool_member(pool_id,(select auth.uid()))
);

drop policy if exists "own notification update" on public.notifications;
create policy "own notification update" on public.notifications
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "admin tournament write" on public.tournaments;
create policy "admin tournament insert" on public.tournaments
for insert to authenticated with check (private.is_admin((select auth.uid())));
create policy "admin tournament update" on public.tournaments
for update to authenticated
using (private.is_admin((select auth.uid())))
with check (private.is_admin((select auth.uid())));
create policy "admin tournament delete" on public.tournaments
for delete to authenticated
using (private.is_admin((select auth.uid())));

drop policy if exists "admin team write" on public.teams;
create policy "admin team insert" on public.teams
for insert to authenticated with check (private.is_admin((select auth.uid())));
create policy "admin team update" on public.teams
for update to authenticated
using (private.is_admin((select auth.uid())))
with check (private.is_admin((select auth.uid())));
create policy "admin team delete" on public.teams
for delete to authenticated
using (private.is_admin((select auth.uid())));

drop policy if exists "admin match write" on public.matches;
create policy "admin match insert" on public.matches
for insert to authenticated with check (private.is_admin((select auth.uid())));
create policy "admin match update" on public.matches
for update to authenticated
using (private.is_admin((select auth.uid())))
with check (private.is_admin((select auth.uid())));
create policy "admin match delete" on public.matches
for delete to authenticated
using (private.is_admin((select auth.uid())));

drop policy if exists "news public read" on public.news_articles;
create policy "news public read" on public.news_articles
for select
using (
  status = 'published'
  or private.is_admin((select auth.uid()))
);

drop policy if exists "admin news write" on public.news_articles;
create policy "admin news insert" on public.news_articles
for insert to authenticated with check (private.is_admin((select auth.uid())));
create policy "admin news update" on public.news_articles
for update to authenticated
using (private.is_admin((select auth.uid())))
with check (private.is_admin((select auth.uid())));
create policy "admin news delete" on public.news_articles
for delete to authenticated
using (private.is_admin((select auth.uid())));

create index if not exists idx_comments_pool_id on public.comments(pool_id);
create index if not exists idx_comments_user_id on public.comments(user_id);
create index if not exists idx_matches_away_team_id on public.matches(away_team_id);
create index if not exists idx_matches_home_team_id on public.matches(home_team_id);
create index if not exists idx_matches_tournament_id on public.matches(tournament_id);
create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_pool_members_user_id on public.pool_members(user_id);
create index if not exists idx_pools_commissioner_id on public.pools(commissioner_id);
create index if not exists idx_pools_tournament_id on public.pools(tournament_id);
create index if not exists idx_predictions_match_id on public.predictions(match_id);
create index if not exists idx_predictions_user_id on public.predictions(user_id);
create index if not exists idx_teams_tournament_id on public.teams(tournament_id);
create index if not exists idx_news_status_published_at on public.news_articles(status,published_at desc);

drop function if exists public.is_admin(uuid);
drop function if exists public.is_pool_member(text,uuid);
