import React,{useState} from 'react'
import { Activity, Newspaper, Shield, Trash2, Trophy, UsersRound } from 'lucide-react'
import { useApp } from '../context/AppContext'
import { Button, Card, Pill, Stat, TeamMark } from '../components/UI'
import { localizedField } from '../i18n'

const emptyNews={category:'platform',title_en:'',title_es:'',title_fr:'',summary_en:'',summary_es:'',summary_fr:'',sourceName:'PoolKick',sourceUrl:'',imageUrl:'',featured:false,status:'published'}

export default function Admin(){
 const {state,currentUser,toggleTournament,setMatchResult,publishNews,deleteNews,t}=useApp()
 const [scores,setScores]=useState({})
 const [newsForm,setNewsForm]=useState(emptyNews)
 const [newsMsg,setNewsMsg]=useState('')
 if(currentUser.role!=='admin')return <Card><h2>{t('admin.only')}</h2></Card>
 const team=id=>state.teams.find(x=>x.id===id)
 const scheduled=state.matches.filter(m=>m.status!=='finished')
 const saveNews=async e=>{e.preventDefault();setNewsMsg('');try{await publishNews(newsForm);setNewsForm(emptyNews);setNewsMsg('✓ Published')}catch(err){setNewsMsg(err.message||'Unable to publish')}}

 return <><div className="page-head"><div><span className="eyebrow">{t('admin.eyebrow')}</span><h1>{t('admin.title')}</h1><p>{t('admin.text')}</p></div><Pill tone="green"><Shield size={14}/> {t('admin.badge')}</Pill></div>
 <div className="stats-grid"><Card><Stat value={state.users.length} label={t('admin.players')}/><UsersRound/></Card><Card><Stat value={state.pools.length} label={t('admin.pools')}/><Trophy/></Card><Card><Stat value={state.predictions.length} label={t('admin.predictions')}/><Activity/></Card><Card><Stat value={state.tournaments.filter(x=>x.status==='active').length} label={t('admin.active')}/><Shield/></Card></div>

 <div className="two-col admin-cols"><Card className="panel"><div className="panel-head"><div><span className="eyebrow">{t('admin.catalogue')}</span><h2>{t('admin.tournaments')}</h2></div></div><div className="admin-tournaments">{state.tournaments.map(x=><div key={x.id}><div className="tourney-icon sm" style={{background:x.accent}}>{x.icon}</div><div><b>{x.name}</b><span>{x.edition}</span></div><Pill tone={x.status==='active'?'green':'default'}>{t(`status.${x.status}`)}</Pill><Button variant="ghost" onClick={()=>toggleTournament(x.id)}>{x.status==='active'?t('admin.deactivate'):t('admin.activate')}</Button></div>)}</div></Card>
 <Card className="panel"><div className="panel-head"><div><span className="eyebrow">{t('admin.health')}</span><h2>{t('admin.system')}</h2></div></div><ul className="status-list"><li><span>{t('admin.auth')}</span><b>{t('admin.ready')}</b></li><li><span>{t('admin.prediction')}</span><b>{t('admin.ready')}</b></li><li><span>{t('admin.scoring')}</span><b>{t('admin.ready')}</b></li><li><span>{t('admin.invites')}</span><b>{t('admin.ready')}</b></li><li><span>{t('admin.notifications')}</span><b>{t('admin.ready')}</b></li><li><span>{t('admin.sportsApi')}</span><em>{t('admin.manualFeed')}</em></li></ul><p className="muted small">{t('admin.dataNote')}</p></Card></div>

 <Card className="panel admin-news-editor"><div className="panel-head"><div><span className="eyebrow">{t('admin.newsOps')}</span><h2>{t('nav.news')}</h2></div><Newspaper/></div><p className="muted">{t('admin.newsHelp')}</p>
 <form className="news-admin-form" onSubmit={saveNews}><div className="form-two"><label>Category<select value={newsForm.category} onChange={e=>setNewsForm({...newsForm,category:e.target.value})}><option value="world-cup">World Cup</option><option value="champions">Champions League</option><option value="copa">Copa América</option><option value="euro">EURO</option><option value="platform">PoolKick</option></select></label><label>Source<input value={newsForm.sourceName} onChange={e=>setNewsForm({...newsForm,sourceName:e.target.value})}/></label></div>
 <div className="news-language-grid"><div><b>English</b><label>Title<input value={newsForm.title_en} onChange={e=>setNewsForm({...newsForm,title_en:e.target.value})} required/></label><label>Summary<textarea value={newsForm.summary_en} onChange={e=>setNewsForm({...newsForm,summary_en:e.target.value})} required/></label></div><div><b>Español</b><label>Título<input value={newsForm.title_es} onChange={e=>setNewsForm({...newsForm,title_es:e.target.value})} required/></label><label>Resumen<textarea value={newsForm.summary_es} onChange={e=>setNewsForm({...newsForm,summary_es:e.target.value})} required/></label></div><div><b>Français</b><label>Titre<input value={newsForm.title_fr} onChange={e=>setNewsForm({...newsForm,title_fr:e.target.value})} required/></label><label>Résumé<textarea value={newsForm.summary_fr} onChange={e=>setNewsForm({...newsForm,summary_fr:e.target.value})} required/></label></div></div>
 <div className="form-two"><label>Source URL<input type="url" value={newsForm.sourceUrl} onChange={e=>setNewsForm({...newsForm,sourceUrl:e.target.value})}/></label><label>Image URL<input type="url" value={newsForm.imageUrl} onChange={e=>setNewsForm({...newsForm,imageUrl:e.target.value})}/></label></div><label className="check-line"><input type="checkbox" checked={newsForm.featured} onChange={e=>setNewsForm({...newsForm,featured:e.target.checked})}/> Featured story</label><Button type="submit">Publish news</Button>{newsMsg&&<span className="small muted">{newsMsg}</span>}</form>
 <div className="admin-news-list">{[...(state.news||[])].sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0)).map(n=><div key={n.id}><div><b>{localizedField(n,'title',state.locale)}</b><span>{n.sourceName||'PoolKick'}</span></div><Button variant="ghost" onClick={()=>deleteNews(n.id)}><Trash2 size={15}/></Button></div>)}</div></Card>

 <Card className="panel admin-results"><div className="panel-head"><div><span className="eyebrow">{t('admin.results')}</span><h2>{t('admin.enterFinal')}</h2></div><span className="muted small">{t('admin.resultNote')}</span></div><div className="admin-match-list">{scheduled.map(m=>{const h=team(m.homeTeamId),a=team(m.awayTeamId),d=scores[m.id]||{home:'',away:''};return <div className="admin-match" key={m.id}><span className="tiny muted">{new Date(m.kickoff).toLocaleDateString()} · {m.round}</span><div><TeamMark team={h} size="sm"/><b>{h.name}</b></div><input type="number" min="0" value={d.home} onChange={e=>setScores(x=>({...x,[m.id]:{...d,home:e.target.value}}))}/><span>–</span><input type="number" min="0" value={d.away} onChange={e=>setScores(x=>({...x,[m.id]:{...d,away:e.target.value}}))}/><div><TeamMark team={a} size="sm"/><b>{a.name}</b></div><Button variant="secondary" disabled={d.home===''||d.away===''} onClick={()=>setMatchResult(m.id,d.home,d.away)}>{t('admin.setFinal')}</Button></div>})}</div></Card></>
}
