import React,{useState} from 'react'
import { Activity, Database, Newspaper, Plus, RefreshCw, Shield, Trash2, Trophy, UsersRound } from 'lucide-react'
import { useApp } from '../context/AppContext'
import { Button, Card, Pill, Stat, TeamMark, TournamentMark } from '../components/UI'
import { localizedField } from '../i18n'
import { featureCopy } from '../featureCopy'

const emptyNews={category:'platform',title_en:'',title_es:'',title_fr:'',summary_en:'',summary_es:'',summary_fr:'',sourceName:'PoolKick',sourceUrl:'',imageUrl:'',featured:false,status:'published'}
const emptyTournament={name:'',shortName:'',edition:'',providerLeagueId:'',providerSeason:'',status:'active'}

import SaveAction from '../components/SaveAction'
import { qaCopy, syncSummary } from '../lib/qa'

export default function Admin(){
 const {state,currentUser,toggleTournament,setMatchResult,publishNews,deleteNews,addTournament,syncTournament,syncAllSports,t,connectionError}=useApp()
 const c=featureCopy(state.locale),q=qaCopy(state.locale)
 const [scores,setScores]=useState({})
 const [newsForm,setNewsForm]=useState(emptyNews)
 const [newsMsg,setNewsMsg]=useState('')
 const [newsBusy,setNewsBusy]=useState(false)
 const [tournamentForm,setTournamentForm]=useState(emptyTournament)
 const [sportsMsg,setSportsMsg]=useState('')
 const [sportsBusy,setSportsBusy]=useState(false)
 if(currentUser.role!=='admin')return <Card><h2>{t('admin.only')}</h2></Card>
 const team=id=>state.teams.find(x=>x.id===id)
 const scheduled=state.matches.filter(m=>m.status!=='finished')
 const saveNews=async e=>{e.preventDefault();setNewsBusy(true);setNewsMsg('');try{await publishNews(newsForm);setNewsForm(emptyNews);setNewsMsg(q.published)}catch(err){setNewsMsg(err.message||q.failed)}finally{setNewsBusy(false)}}
 const saveTournament=async e=>{e.preventDefault();setSportsBusy(true);setSportsMsg('');try{const saved=await addTournament(tournamentForm);setTournamentForm(emptyTournament);setSportsMsg(q.created+(saved.syncWarning?' '+saved.syncWarning:''))}catch(err){setSportsMsg(err.message||'Unable to create tournament.')}finally{setSportsBusy(false)}}
 const syncAll=async()=>{setSportsBusy(true);setSportsMsg('');try{const r=await syncAllSports();setSportsMsg(syncSummary(r,state.locale))}catch(err){setSportsMsg(err.message||'Sync failed.')}finally{setSportsBusy(false)}}
 const syncOne=async id=>{setSportsBusy(true);setSportsMsg('');try{const r=await syncTournament(id);setSportsMsg(syncSummary(r,state.locale))}catch(err){setSportsMsg(err.message||'Sync failed.')}finally{setSportsBusy(false)}}

 return <><div className="page-head"><div><span className="eyebrow">{t('admin.eyebrow')}</span><h1>{t('admin.title')}</h1><p>{t('admin.text')}</p></div><Pill tone="green"><Shield size={14}/> {t('admin.badge')}</Pill></div>
 <div className="stats-grid"><Card><Stat value={state.users.length} label={t('admin.players')}/><UsersRound/></Card><Card><Stat value={state.pools.length} label={t('admin.pools')}/><Trophy/></Card><Card><Stat value={state.predictions.length} label={t('admin.predictions')}/><Activity/></Card><Card><Stat value={state.tournaments.filter(x=>x.status==='active').length} label={t('admin.active')}/><Shield/></Card></div>

 <Card className="panel sports-admin"><div className="panel-head"><div><span className="eyebrow">{c.realData}</span><h2>{c.provider}: TheSportsDB</h2></div><Button variant="secondary" onClick={syncAll} disabled={sportsBusy}><RefreshCw size={16} className={sportsBusy?'spin':''}/>{sportsBusy?c.syncing:c.sync}</Button></div><p className="muted">{c.autoSync} {c.freeTier}</p>{sportsMsg&&<div className="sync-message">{sportsMsg}</div>}
 <div className="admin-tournaments live-admin-list">{state.tournaments.map(x=><div key={x.id}><TournamentMark tournament={x} size="sm"/><div><b>{x.name}</b><span>{x.edition} · ID {x.providerLeagueId||'—'} · {x.providerSeason||'—'}</span><small>{x.lastSyncedAt?`${c.lastSync}: ${new Date(x.lastSyncedAt).toLocaleString()}`:q.notSynced}</small></div><Pill tone={x.status==='active'?'green':'default'}>{t(`status.${x.status}`)}</Pill><Button variant="ghost" onClick={()=>syncOne(x.id)} disabled={sportsBusy||!x.providerLeagueId}><RefreshCw size={14}/>{c.sync}</Button><SaveAction variant="ghost" action={()=>toggleTournament(x.id)}>{x.status==='active'?t('admin.deactivate'):t('admin.activate')}</SaveAction></div>)}</div>
 <form className="tournament-add-form" onSubmit={saveTournament}><div className="section-title"><div><span className="eyebrow">{c.addTournament}</span><h3>{c.autoSync}</h3></div><Plus/></div><div className="form-two"><label>{q.name}<input value={tournamentForm.name} onChange={e=>setTournamentForm({...tournamentForm,name:e.target.value})} placeholder="UEFA Europa League" required/></label><label>{c.shortName}<input value={tournamentForm.shortName} onChange={e=>setTournamentForm({...tournamentForm,shortName:e.target.value})} placeholder="UEL" required/></label></div><div className="form-two"><label>{q.edition}<input value={tournamentForm.edition} onChange={e=>setTournamentForm({...tournamentForm,edition:e.target.value})} placeholder="2026/27" required/></label><label>{c.season}<input value={tournamentForm.providerSeason} onChange={e=>setTournamentForm({...tournamentForm,providerSeason:e.target.value})} placeholder="2026-2027" required/></label></div><label>{c.leagueId}<input value={tournamentForm.providerLeagueId} onChange={e=>setTournamentForm({...tournamentForm,providerLeagueId:e.target.value})} placeholder="TheSportsDB league ID" required/></label><Button type="submit" disabled={sportsBusy}><Database size={16}/>{c.createSync}</Button></form></Card>

 <div className="two-col admin-cols"><Card className="panel"><div className="panel-head"><div><span className="eyebrow">{t('admin.catalogue')}</span><h2>{t('admin.tournaments')}</h2></div></div><div className="admin-tournaments">{state.tournaments.map(x=><div key={x.id}><TournamentMark tournament={x} size="sm"/><div><b>{x.name}</b><span>{x.edition}</span></div><Pill tone={x.status==='active'?'green':'default'}>{t(`status.${x.status}`)}</Pill><SaveAction variant="ghost" action={()=>toggleTournament(x.id)}>{x.status==='active'?t('admin.deactivate'):t('admin.activate')}</SaveAction></div>)}</div></Card>
 <Card className="panel"><div className="panel-head"><div><span className="eyebrow">{t('admin.health')}</span><h2>{t('admin.system')}</h2></div></div><ul className="status-list"><li><span>{t('admin.auth')}</span><b>{currentUser?.id?currentUser.displayName:q.unverified}</b></li><li><span>{q.dataLoaded}</span><b>{connectionError?q.unverified:state.tournaments.length}</b></li><li><span>{t('admin.sportsApi')}</span><b>{state.tournaments.filter(x=>x.lastSyncedAt).length}/{state.tournaments.length}</b></li></ul><p className="muted small">{q.sportsLimited}</p></Card></div>

 <Card className="panel admin-news-editor"><div className="panel-head"><div><span className="eyebrow">{t('admin.newsOps')}</span><h2>{t('nav.news')}</h2></div><Newspaper/></div><p className="muted">{t('admin.newsHelp')}</p>
 <form className="news-admin-form" onSubmit={saveNews}><div className="form-two"><label>{q.category}<select value={newsForm.category} onChange={e=>setNewsForm({...newsForm,category:e.target.value})}><option value="world-cup">World Cup</option><option value="champions">Champions League</option><option value="copa">Copa América</option><option value="euro">EURO</option><option value="platform">PoolKick</option></select></label><label>{q.source}<input value={newsForm.sourceName} onChange={e=>setNewsForm({...newsForm,sourceName:e.target.value})}/></label></div>
 <div className="news-language-grid"><div><b>English</b><label>Title<input value={newsForm.title_en} onChange={e=>setNewsForm({...newsForm,title_en:e.target.value})} required/></label><label>Summary<textarea value={newsForm.summary_en} onChange={e=>setNewsForm({...newsForm,summary_en:e.target.value})} required/></label></div><div><b>Español</b><label>Título<input value={newsForm.title_es} onChange={e=>setNewsForm({...newsForm,title_es:e.target.value})} required/></label><label>Resumen<textarea value={newsForm.summary_es} onChange={e=>setNewsForm({...newsForm,summary_es:e.target.value})} required/></label></div><div><b>Français</b><label>Titre<input value={newsForm.title_fr} onChange={e=>setNewsForm({...newsForm,title_fr:e.target.value})} required/></label><label>Résumé<textarea value={newsForm.summary_fr} onChange={e=>setNewsForm({...newsForm,summary_fr:e.target.value})} required/></label></div></div>
 <div className="form-two"><label>{q.sourceUrl}<input type="url" value={newsForm.sourceUrl} onChange={e=>setNewsForm({...newsForm,sourceUrl:e.target.value})}/></label><label>{q.imageUrl}<input type="url" value={newsForm.imageUrl} onChange={e=>setNewsForm({...newsForm,imageUrl:e.target.value})}/></label></div><label className="check-line"><input type="checkbox" checked={newsForm.featured} onChange={e=>setNewsForm({...newsForm,featured:e.target.checked})}/> {q.featured}</label><Button type="submit" className="full" disabled={newsBusy}>{newsBusy?q.saving:q.publish}</Button>{newsMsg&&<span className="small muted">{newsMsg}</span>}</form>
 <div className="admin-news-list">{[...(state.news||[])].filter(n=>n.status==='published').sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0)).map(n=><div key={n.id}><div><b>{localizedField(n,'title',state.locale)}</b><span>{n.sourceName||'PoolKick'}</span></div><SaveAction variant="ghost" action={()=>deleteNews(n.id)} success={q.archived} aria-label={q.archive}><Trash2 size={15}/></SaveAction></div>)}</div></Card>

 <Card className="panel admin-results"><div className="panel-head"><div><span className="eyebrow">{t('admin.results')}</span><h2>{t('admin.enterFinal')}</h2></div><span className="muted small">{t('admin.resultNote')}</span></div><div className="admin-match-list">{scheduled.slice(0,30).map(m=>{const h=team(m.homeTeamId),a=team(m.awayTeamId),d=scores[m.id]||{home:'',away:''};return <div className="admin-match" key={m.id}><span className="tiny muted">{new Date(m.kickoff).toLocaleDateString()} · {m.round}</span><div><TeamMark team={h} size="sm"/><b>{h?.name||'TBD'}</b></div><input aria-label={`${h?.name||'Home'} score`} type="number" min="0" step="1" value={d.home} onChange={e=>setScores(x=>({...x,[m.id]:{...d,home:e.target.value}}))}/><span>–</span><input aria-label={`${a?.name||'Away'} score`} type="number" min="0" step="1" value={d.away} onChange={e=>setScores(x=>({...x,[m.id]:{...d,away:e.target.value}}))}/><div><TeamMark team={a} size="sm"/><b>{a?.name||'TBD'}</b></div><SaveAction variant="secondary" disabled={d.home===''||d.away===''} action={()=>setMatchResult(m.id,d.home,d.away)}>{t('admin.setFinal')}</SaveAction></div>})}</div></Card></>
}
