import React, {useState} from 'react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { CheckCircle2, ChevronRight, Trophy, UsersRound, Zap } from 'lucide-react'
import { APP } from '../config'
import { useApp } from '../context/AppContext'
import { Button, Card } from '../components/UI'

export default function Landing(){
  const {currentUser,login,signup}=useApp(); const nav=useNavigate(); const [auth,setAuth]=useState(null); const [form,setForm]=useState({email:'adrian@poolkick.demo',password:'demo',displayName:'Adrian'}); const [err,setErr]=useState('')
  if(currentUser) return <Navigate to="/dashboard" replace/>
  const submit=async(e)=>{e.preventDefault();setErr('');try{auth==='signup'?await signup(form):await login(form.email,form.password);nav('/dashboard')}catch(x){setErr(x.message)}}
  return <div className="landing">
    <header className="public-nav"><a className="brand" href="#top"><span className="brand-ball">⚽</span><span>{APP.name}</span></a><div><a href="#how">How it works</a><a href="#features">Features</a><Link to="/manual-public">Manual</Link><Button variant="ghost" onClick={()=>setAuth('login')}>Sign in</Button><Button onClick={()=>setAuth('signup')}>Create profile</Button></div></header>
    <section className="hero" id="top"><div className="hero-copy"><span className="eyebrow">Football is better together</span><h1>Predict. Compete.<br/><em>Brag.</em></h1><p>Create private football prediction pools with friends, call the scores, earn points and climb the table — tournament by tournament.</p><div className="hero-actions"><Button onClick={()=>setAuth('signup')}>Create a pool <ChevronRight size={18}/></Button><Button variant="secondary" onClick={()=>setAuth('login')}>Join your friends</Button></div><div className="trust-row"><span><CheckCircle2/> No betting</span><span><CheckCircle2/> Private groups</span><span><CheckCircle2/> Mobile first</span></div></div>
      <div className="hero-card-wrap"><Card className="hero-score-card"><div className="live-label"><span/> MATCHDAY 1 · PICKS OPEN</div><h3>The Crew — World Cup</h3><div className="hero-match"><div><b>🇨🇴</b><span>Colombia</span></div><div className="score-pick"><i>2</i><span>–</span><i>1</i><small>Your pick</small></div><div><b>🇦🇷</b><span>Argentina</span></div></div><div className="mini-table"><div><b>1</b><span>🦁 Adrian</span><strong>42 pts</strong></div><div><b>2</b><span>🦊 Marlon</span><strong>40 pts</strong></div><div><b>3</b><span>🦅 Luisa</span><strong>36 pts</strong></div></div></Card><div className="float-badge">🔥 5 pick streak</div></div>
    </section>
    <section className="tournament-strip"><span>Built for tournaments</span><div><b>🌎 World Cup</b><b>🏆 Champions League</b><b>🇪🇺 EURO</b><b>🌎 Copa América</b></div></section>
    <section className="section" id="how"><span className="eyebrow">Three simple steps</span><h2>From invite to leaderboard in minutes.</h2><div className="three-grid">{[['01','Choose a tournament','Start with the competition everyone is already talking about.'],['02','Create your private pool','Name it, pick a scoring format, then share the invitation code.'],['03','Predict and compete','Enter scores before kickoff. PoolKick calculates points and standings automatically.']].map(x=><Card key={x[0]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></Card>)}</div></section>
    <section className="section feature-section" id="features"><div><span className="eyebrow">Everything the group needs</span><h2>More fun than a spreadsheet. Easier than fantasy.</h2><p>Private pools, hidden pre-match picks, automatic scoring, profiles, avatars, chat, stats and commissioner controls — all in one place.</p></div><div className="feature-grid"><div><Trophy/><b>Automatic standings</b><span>Points update as results are recorded.</span></div><div><UsersRound/><b>Private social pools</b><span>Invite friends with a short code.</span></div><div><Zap/><b>Kickoff locking</b><span>Picks freeze automatically when matches begin.</span></div></div></section>
    <footer><div className="brand">⚽ {APP.name}</div><p>Social football predictions. Built for fun, not wagering.</p><small>© 2026 {APP.name}. Temporary project branding.</small></footer>
    {auth&&<div className="modal-backdrop" onMouseDown={()=>setAuth(null)}><div className="auth-modal" onMouseDown={e=>e.stopPropagation()}><button className="close-x" onClick={()=>setAuth(null)}>×</button><div className="brand center">⚽ {APP.name}</div><h2>{auth==='signup'?'Create your player profile':'Welcome back'}</h2><p className="muted">{auth==='signup'?'You can join or create a pool right away.':'Sign in to see your pools and picks.'}</p><form onSubmit={submit}>{auth==='signup'&&<label>Display name<input value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})} required/></label>}<label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label>{err&&<div className="form-error">{err}</div>}<Button type="submit" className="full">{auth==='signup'?'Create profile':'Sign in'}</Button></form><div className="demo-note"><b>Demo access</b><span>Use adrian@poolkick.demo or marlon@poolkick.demo. Any password works in Demo Mode.</span></div></div></div>}
  </div>
}
