import React,{useState} from 'react'
import { Link } from 'react-router-dom'
import { BookOpen, CheckCircle2, CircleHelp, Crown, LockKeyhole, MessageCircle, Shield, Trophy, UserPlus, UsersRound } from 'lucide-react'
import { APP } from '../config'

const sections=[
['start','1. What PoolKick is'],['account','2. Account & profile'],['join','3. Join a pool'],['create','4. Create a pool'],['picks','5. Make predictions'],['scoring','6. Scoring'],['leaderboard','7. Leaderboard'],['chat','8. Pool chat'],['commissioner','9. Commissioner'],['admin','10. Platform admin'],['faq','11. FAQ']]

export default function Manual({publicView=false}){const [active,setActive]=useState('start');return <div className={publicView?'manual-public':''}>{publicView&&<header className="manual-public-head"><Link to="/" className="brand">⚽ {APP.name}</Link><Link to="/">Back home</Link></header>}<div className="manual-layout"><aside className="manual-nav"><div><BookOpen/><b>User Manual</b></div>{sections.map(s=><button key={s[0]} className={active===s[0]?'active':''} onClick={()=>{setActive(s[0]);document.getElementById(s[0])?.scrollIntoView({behavior:'smooth'})}}>{s[1]}</button>)}</aside><article className="manual-content"><span className="eyebrow">Complete operating guide</span><h1>How to use {APP.name}</h1><p className="lead">This manual is designed so a first-time player, pool commissioner or administrator can understand the platform without outside help.</p>
<section id="start"><h2>1. What PoolKick is</h2><p>PoolKick is a social football prediction platform built around major tournaments. A player joins a private pool with friends, predicts match scores before kickoff, earns points when the real result is known and competes on a live leaderboard.</p><div className="manual-callout"><Trophy/><div><b>It is a prediction game, not a sportsbook.</b><span>The platform does not require wagers or process prize money. The core experience is competition, statistics and friendly bragging rights.</span></div></div><h3>The basic flow</h3><ol><li>Create a player profile.</li><li>Join an existing private pool with its invite code, or create a new pool.</li><li>Open the tournament schedule and enter a predicted score for every match.</li><li>Save each pick before the official kickoff time.</li><li>When a match finishes, the result is recorded and points are calculated automatically.</li><li>Check the leaderboard and pool chat.</li></ol></section>
<section id="account"><h2>2. Account and profile</h2><div className="manual-icon"><UserPlus/></div><p>Use <b>Create profile</b> from the home page. Enter a display name, email and password. In production mode, authentication is handled by Supabase Auth. In Demo Mode, any password is accepted for the included demo accounts.</p><h3>Customize your profile</h3><p>Open <b>Profile</b> from the left menu. You can change your display name, choose an avatar, add a country flag and record a favorite team. These details appear in pool member lists, chat and leaderboards.</p><div className="manual-tip"><b>Tip:</b> Keep the display name recognizable to your friends. Your login email is not shown in the public leaderboard.</div></section>
<section id="join"><h2>3. Join an existing pool</h2><div className="manual-icon"><UsersRound/></div><ol><li>Sign in.</li><li>Open <b>My Pools</b>.</li><li>Select <b>Join with code</b>.</li><li>Enter the invitation code received from the commissioner, for example <code>CREW26</code>.</li><li>Select <b>Join pool</b>.</li></ol><p>You are added immediately. The pool appears in <b>My Pools</b> and its tournament matches become available for your predictions.</p></section>
<section id="create"><h2>4. Create a new pool</h2><div className="manual-icon"><Crown/></div><ol><li>Open <b>My Pools</b>.</li><li>Select <b>Create pool</b>.</li><li>Give the pool a recognizable name.</li><li>Choose the tournament.</li><li>Choose the scoring preset.</li><li>Create the pool.</li></ol><p>PoolKick generates a short invite code. Share that code through WhatsApp, email, text or any other channel. Anyone with the code can join after creating a player profile.</p><h3>Scoring is locked after creation</h3><p>Changing scoring in the middle of a competition can be unfair. For that reason, V1 treats the selected scoring preset as fixed for the life of the pool.</p></section>
<section id="picks"><h2>5. Make match predictions</h2><div className="manual-icon"><LockKeyhole/></div><p>Open a pool and select <b>My picks</b>. Each scheduled match has two score boxes: one for the home team and one for the away team. Enter whole numbers such as 2 and 1, then press <b>Save pick</b>.</p><h3>Kickoff lock</h3><p>The prediction can be changed as many times as you want before kickoff. At kickoff, the fields lock automatically. This prevents late edits based on events in the match.</p><h3>Hidden predictions</h3><p>Before kickoff, another player's score prediction should not be visible to you. This avoids copying. After the match is underway or complete, the platform can expose picks for transparency and social discussion.</p><div className="manual-callout"><LockKeyhole/><div><b>Deadline rule</b><span>The platform uses the match kickoff timestamp. If your device clock and the server disagree, the server timestamp should be authoritative in production.</span></div></div></section>
<section id="scoring"><h2>6. Scoring</h2><p>Each pool selects one scoring preset when it is created.</p><div className="manual-table"><div><b>Classic 5–3–2</b><span>Exact score</span><strong>5 pts</strong><span>Correct goal difference</span><strong>3 pts</strong><span>Correct winner/draw</span><strong>2 pts</strong><span>Wrong result</span><strong>0 pts</strong></div><div><b>Simple 3–1</b><span>Exact score</span><strong>3 pts</strong><span>Correct winner/draw</span><strong>1 pt</strong><span>Wrong result</span><strong>0 pts</strong></div></div><h3>Example</h3><p>If the final score is Colombia 2–1 Argentina and you predicted 2–1, you receive exact-score points. If you predicted 3–2 under Classic, the winner and goal difference are both correct, so you receive 3 points. If you predicted 1–0, you still chose the correct winner and receive 2 points.</p></section>
<section id="leaderboard"><h2>7. Leaderboard</h2><div className="manual-icon"><Trophy/></div><p>Open any pool and select <b>Leaderboard</b>. Players are sorted by total points. Exact scores are used as the first tie-breaker in the current version. The table also shows the number of correct predictions.</p><p>Your own row is highlighted. The commissioner is labeled so players always know who manages the group.</p></section>
<section id="chat"><h2>8. Pool chat</h2><div className="manual-icon"><MessageCircle/></div><p>The <b>Pool chat</b> tab is a private conversation space for members of that pool. Use it for reminders, reactions, friendly trash talk and tournament discussion. Messages show the player's avatar, name and timestamp.</p></section>
<section id="commissioner"><h2>9. Commissioner guide</h2><div className="manual-icon"><Crown/></div><p>The person who creates a pool is its commissioner. The commissioner does not control official match results or secretly edit other players' picks. The role is intentionally social and organizational.</p><h3>Commissioner responsibilities</h3><ul className="check-list"><li><CheckCircle2/> Share the invitation code.</li><li><CheckCircle2/> Tell players which scoring preset is being used.</li><li><CheckCircle2/> Remind the group that picks lock at kickoff.</li><li><CheckCircle2/> Use chat for pool-specific communication.</li><li><CheckCircle2/> Help members confirm they joined the correct pool.</li></ul></section>
<section id="admin"><h2>10. Platform administrator guide</h2><div className="manual-icon"><Shield/></div><p>A platform administrator has access to <b>Admin</b> in the left navigation. This is different from being a pool commissioner.</p><h3>Tournament catalogue</h3><p>The administrator can activate or deactivate tournaments. An active tournament is available for new pools. A coming/inactive tournament remains in the catalogue but cannot be selected for new competition until activated.</p><h3>Result operator</h3><p>For any scheduled match, enter the final home and away score and select <b>Set final</b>. The scoring engine then recalculates all predictions tied to that match and updates every affected pool leaderboard.</p><h3>Sports data API</h3><p>The included V1 can be operated manually, which is useful for testing and keeps the project at zero external API cost. The database structure is ready for a licensed football-data provider to populate teams, fixtures, kickoff times and results automatically later.</p></section>
<section id="faq"><h2>11. Frequently asked questions</h2><div className="faq"><details><summary>Can I change a pick?</summary><p>Yes, until kickoff. After kickoff the match is locked.</p></details><details><summary>Can I see my friends' picks before a match?</summary><p>The intended production behavior is no. Picks remain private until the deadline has passed.</p></details><details><summary>Can one person join several pools?</summary><p>Yes. The same user can join many pools, including several pools for the same tournament.</p></details><details><summary>Are points shared between pools?</summary><p>No. Each pool has its own scoring preset and leaderboard.</p></details><details><summary>Can we add Libertadores, Gold Cup or Club World Cup later?</summary><p>Yes. The platform uses tournament, stage, match and team entities instead of hard-coding one specific competition format.</p></details><details><summary>Does the platform charge money?</summary><p>The current build has no payment flow and no wagering functionality.</p></details><details><summary>How do I replace the temporary PoolKick brand?</summary><p>Update the application name in <code>src/config.js</code> and the design variables in <code>src/styles.css</code>. The final Marlon logo can then replace the temporary football mark.</p></details></div></section>
<div className="manual-end"><CircleHelp/><div><b>Still unsure?</b><span>Start in Demo Mode and use code <code>CREW26</code>. Every major workflow is already populated with sample data so a reviewer can learn by clicking through the platform.</span></div></div></article></div></div>}
