import React,{useState} from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { Copy, Plus, UsersRound } from 'lucide-react'
import { useApp } from '../context/AppContext'
import { Button, Card, Pill } from '../components/UI'
import { standingsForPool } from '../lib/scoring'

export default function Pools(){const {state,currentUser,createPool,joinPool}=useApp();const nav=useNavigate();const [create,setCreate]=useState(false);const [join,setJoin]=useState(false);const [code,setCode]=useState('');const [form,setForm]=useState({tournamentId:state.tournaments.find(t=>t.status==='active')?.id,name:'',scoring:'classic',visibility:'private'});const pools=state.pools.filter(p=>p.members.includes(currentUser.id));
const make=e=>{e.preventDefault();const p=createPool(form);setCreate(false);nav(`/pools/${p.id}`)};const doJoin=async e=>{e.preventDefault();try{const p=await joinPool(code);if(p)nav(`/pools/${p.id}`);else alert('Pool code not found.')}catch(err){alert(err.message||'Unable to join pool.')}}
return <><div className="page-head"><div><span className="eyebrow">Your groups</span><h1>My prediction pools.</h1><p>Create a private contest, share a code and let the football arguments begin.</p></div><div className="head-actions"><Button variant="secondary" onClick={()=>setJoin(true)}>Join with code</Button><Button onClick={()=>setCreate(true)}><Plus size={17}/> Create pool</Button></div></div>
<div className="pool-grid">{pools.map(p=>{const t=state.tournaments.find(x=>x.id===p.tournamentId);const standings=standingsForPool(state,p.id);const rank=standings.findIndex(x=>x.user.id===currentUser.id)+1;return <Link to={`/pools/${p.id}`} key={p.id} className="pool-card"><div className="pool-top"><div className="tourney-icon" style={{background:t?.accent}}>{t?.icon}</div><Pill tone="green">{t?.shortName}</Pill></div><h2>{p.name}</h2><p>{t?.name} {t?.edition}</p><div className="pool-metrics"><span><UsersRound size={17}/>{p.members.length} players</span><span>#{rank} your rank</span></div><div className="pool-code"><span>Invite code</span><b>{p.code}</b><Copy size={16}/></div></Link>})}</div>
{create&&<div className="modal-backdrop"><form className="auth-modal" onSubmit={make}><button type="button" className="close-x" onClick={()=>setCreate(false)}>×</button><span className="eyebrow">New pool</span><h2>Create a competition</h2><label>Pool name<input placeholder="e.g. The Crew — World Cup" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Tournament<select value={form.tournamentId} onChange={e=>setForm({...form,tournamentId:e.target.value})}>{state.tournaments.filter(t=>t.status==='active').map(t=><option key={t.id} value={t.id}>{t.name} {t.edition}</option>)}</select></label><label>Scoring<select value={form.scoring} onChange={e=>setForm({...form,scoring:e.target.value})}><option value="classic">Classic — 5 exact / 3 difference / 2 outcome</option><option value="simple">Simple — 3 exact / 1 correct result</option></select></label><Button type="submit" className="full">Create & get invite code</Button></form></div>}
{join&&<div className="modal-backdrop"><form className="auth-modal" onSubmit={doJoin}><button type="button" className="close-x" onClick={()=>setJoin(false)}>×</button><span className="eyebrow">Invitation</span><h2>Join a pool</h2><label>Pool code<input className="code-input" placeholder="CREW26" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} required/></label><Button type="submit" className="full">Join pool</Button><div className="demo-note">Try the demo code <b>CREW26</b>.</div></form></div>}</>}
