import React, {useState} from 'react'
import { useApp } from '../context/AppContext'
import { Button, Card, Pill, TeamMark } from '../components/UI'

export default function Tournaments(){
 const {state,currentUser,savePrediction}=useApp(); const [selected,setSelected]=useState(state.tournaments.find(t=>t.status==='active')?.id); const [drafts,setDrafts]=useState({}); const tournament=state.tournaments.find(t=>t.id===selected); const matches=state.matches.filter(m=>m.tournamentId===selected).sort((a,b)=>new Date(a.kickoff)-new Date(b.kickoff)); const team=id=>state.teams.find(t=>t.id===id); const userPools=state.pools.filter(p=>p.tournamentId===selected&&p.members.includes(currentUser.id)); const pool=userPools[0]
 const pick=(m,side,val)=>setDrafts(d=>({...d,[m.id]:{home:d[m.id]?.home??'',away:d[m.id]?.away??'',[side]:val}}));
 return <><div className="page-head"><div><span className="eyebrow">Tournament hub</span><h1>Pick the competition.</h1><p>Each tournament has its own matches and stages, while your private pools keep separate leaderboards and scoring rules.</p></div></div>
 <div className="tournament-cards">{state.tournaments.map(t=><button key={t.id} onClick={()=>setSelected(t.id)} className={`tournament-card ${selected===t.id?'selected':''}`}><div className="tourney-icon" style={{background:t.accent}}>{t.icon}</div><div><b>{t.name}</b><span>{t.edition}</span></div><Pill tone={t.status==='active'?'green':'default'}>{t.status}</Pill></button>)}</div>
 {tournament&&<Card className="tourney-detail"><div className="tourney-banner"><div className="tourney-icon large" style={{background:tournament.accent}}>{tournament.icon}</div><div><span className="eyebrow">{tournament.edition}</span><h2>{tournament.name}</h2><p>{tournament.description}</p></div><div className="format-box"><small>Format</small><b>{tournament.format}</b></div></div></Card>}
 <div className="section-title"><div><span className="eyebrow">Schedule</span><h2>Matches & your picks</h2></div>{pool?<Pill tone="green">Playing in {pool.name}</Pill>:<Pill>Join/create a pool to save picks</Pill>}</div>
 <div className="fixtures">{matches.map(m=>{const h=team(m.homeTeamId),a=team(m.awayTeamId); const existing=pool&&state.predictions.find(p=>p.poolId===pool.id&&p.matchId===m.id&&p.userId===currentUser.id); const locked=new Date(m.kickoff)<=new Date(); const d=drafts[m.id]||{home:existing?.homeScore??'',away:existing?.awayScore??''}; return <Card className="fixture" key={m.id}><div className="fixture-meta"><span>{m.stage} · {m.round}</span><b>{m.status==='finished'?'FINAL':new Date(m.kickoff).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</b></div><div className="fixture-main"><div className="fixture-team"><TeamMark team={h}/><b>{h.name}</b></div><div className="predict-box">{m.status==='finished'?<div className="final-score"><strong>{m.homeScore}</strong><span>–</span><strong>{m.awayScore}</strong></div>:<><div><input aria-label={`${h.name} score`} type="number" min="0" value={d.home} disabled={locked} onChange={e=>pick(m,'home',e.target.value)}/><span>–</span><input aria-label={`${a.name} score`} type="number" min="0" value={d.away} disabled={locked} onChange={e=>pick(m,'away',e.target.value)}/></div><small>{locked?'🔒 Picks locked':'Your prediction'}</small></>}</div><div className="fixture-team right"><TeamMark team={a}/><b>{a.name}</b></div></div>{m.status!=='finished'&&pool&&!locked&&<Button variant="secondary" className="save-pick" disabled={d.home===''||d.away===''} onClick={()=>savePrediction(pool.id,m.id,d.home,d.away)}>{existing?'Update pick':'Save pick'}</Button>}{existing&&m.status==='finished'&&<div className="points-earned">Your pick: {existing.homeScore}–{existing.awayScore} · <b>{existing.points} pts</b></div>}</Card>})}</div></>
}
